class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror9'
        self.UnzipMirrorCommand = 'unzipmirror9'
        self.TarMirrorCommand = 'tarmirror9'
        self.ZipMirrorCommand = 'zipmirror9'
        self.CancelMirror = 'cancel9'
        self.CancelAllCommand = 'cancelall9'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart9'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone9'
        self.CountCommand = 'count9'
        self.WatchCommand = 'watch9'
        self.TarWatchCommand = 'tarwatch9'
        self.DeleteCommand = 'del9'
        self.ConfigMenuCommand = 'config9'
        self.ShellCommand = 'shell9'
        self.UpdateCommand = 'update9'
        self.ExecHelpCommand = 'exechelp9'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
